using System;
using System.Globalization;

namespace WebApi.Helpers
{   
    ///<Summary>
    /// It is a custom exception class to be reused for throwing exceptions generated by the application like for validation. 
    ///</Summary>
    public class AppException : Exception
    {
        public AppException() : base() {}

        /// <param name="message"> The exception message to be displayed to the user.</param>
        public AppException(string message) : base(message) { }


        /// <param name="message"> The exception message to be displayed to the user.</param>
        /// /// <param name="args"> The exception message to be formatted and displayed to the user.</param>
        public AppException(string message, params object[] args) 
            : base(String.Format(CultureInfo.CurrentCulture, message, args))
        {
        }
    }
}